{{- if .Values.stac.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stac-envvar-configmap
data:
  {{- range $envKey, $envValue := .Values.stac.settings.envVars }}
  {{ upper $envKey }}: "{{ $envValue }}"
  {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stac-{{ .Values.gitSha }}
  name: stac-{{ .Values.gitSha }}
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: stac-{{ .Values.gitSha }}
  template:
    metadata:
      labels:
        app: stac-{{ .Values.gitSha }}
    spec:
      containers:
      - image: {{ .Values.stac.image.name }}:{{ .Values.stac.image.tag }}
        name: stac
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: {{ .Values.stac.settings.resources.limits.cpu }}
            memory: {{ .Values.stac.settings.resources.limits.memory }}
          requests:
            cpu: {{ .Values.stac.settings.resources.requests.cpu }}
            memory: {{ .Values.stac.settings.resources.requests.memory }}
        env:
          # NOTE: there's no reason we need to use a `ConfigMap` here to get os env vars into the pod.
          # we could just template them out here immediately with `value: $_` but this allows us
          # to store them in k8s intermediately and change them and then bounce deploys if needed
          {{- range $envKey, $_ := .Values.stac.settings.envVars }}
          - name: {{ upper $envKey }}
            valueFrom:
              configMapKeyRef:
                name: stac-envvar-configmap
                key: {{ upper $envKey }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: stac-{{ .Values.gitSha }}
  name: stac
spec:
  type: 'NodePort'
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 32453
  selector:
    app: stac-{{ .Values.gitSha }}
{{- end }}
