{{- if .Values.vector.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-configmap
data:
  {{- range $envKey, $envValue := .Values.vector.settings.envVars }}
  {{ upper $envKey }}: {{ $envValue }}
  {{- end }}
{{- end }}
