{{- if .Values.vector.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vector-{{ .Values.gitSha }}
  name: vector-{{ .Values.gitSha }}
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: vector-{{ .Values.gitSha }}
  template:
    metadata:
      labels:
        app: vector-{{ .Values.gitSha }}
    spec:
      containers:
      - image: ghcr.io/vincentsarago/uvicorn-gunicorn:3.11
        name: vector
        ports:
          - containerPort: 8080
        resources: {{ .Values.vector.settings.resources }}
        env:
          # NOTE: there's no reason we need to use a `ConfigMap` here to get os env vars into the pod.
          # we could just template them out here immediately with `value: $_` but this allows us
          # to store them in k8s intermediately and change them and then bounce deploys if needed
          {{- range $envKey, $_ := .Values.vector.settings.envVars }}
          - name: {{ upper $envKey }}
            valueFrom:
              configMapKeyRef:
                name: vector-configmap
                key: {{ $envKey }}
          {{- end }}
{{- end }}
