{{- if .Values.vector.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-envvar-configmap
data:
  {{- range $envKey, $envValue := .Values.vector.settings.envVars }}
  {{ upper $envKey }}: "{{ $envValue }}"
  {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vector
    gitsha: {{ .Values.gitSha }}
  name: vector
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: vector
  template:
    metadata:
      labels:
        app: vector
    spec:
      containers:
      - image: {{ .Values.vector.image.name }}:{{ .Values.vector.image.tag }}
        name: vector
        ports:
          - containerPort: {{ .Values.vector.service.port  }}
        resources:
          limits:
            cpu: {{ .Values.vector.settings.resources.limits.cpu }}
            memory: {{ .Values.vector.settings.resources.limits.memory }}
          requests:
            cpu: {{ .Values.vector.settings.resources.requests.cpu }}
            memory: {{ .Values.vector.settings.resources.requests.memory }}
        env:
          # NOTE: there's no reason we need to use a `ConfigMap` or `Secret` here to get os env vars into the pod.
          # we could just template them out here immediately with `value: $_` but this allows us
          # to store them in k8s intermediately and change them and then bounce deploys if needed
          {{- range $envKey, $_ := .Values.db.settings.secrets }}
          - name: {{ upper $envKey }}
            valueFrom:
              secretKeyRef:
                name: pgstac-secrets
                key: {{ upper $envKey }}
          {{- end }}
          {{- range $envKey, $_ := .Values.vector.settings.envVars }}
          - name: {{ upper $envKey }}
            valueFrom:
              configMapKeyRef:
                name: vector-envvar-configmap
                key: {{ upper $envKey }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vector
  name: vector
spec:
  type: 'NodePort'
  ports:
  - name: "{{ .Values.vector.service.port }}"
    port: {{ .Values.vector.service.port }}
    targetPort: {{ .Values.vector.service.port }}
  selector:
    app: vector
---
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: vector
  {{- with .Values.vector.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.vector.enable_shared_ingress }}
    alb.ingress.kubernetes.io/group.name: shared-ingress
  {{- end }}
spec:
  {{- if and .Values.vector.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.vector.ingress.className }}
  {{- end }}
  rules:
    - http:
        paths:
          - pathType: Prefix
            {{- if .Values.vector.enable_shared_ingress }}
            path: {{ .Values.vector.ingress.path }}
            {{ else }}
            path: "/"
            {{- end }}
            backend:
              service:
                name: vector
                port:
                  number: {{ .Values.vector.service.port  }}
{{- end }}
