apiVersion: v1
kind: Service
metadata:
  labels:
    app: vector-{{ .Values.gitSha }}
  name: vector
spec:
  type: 'NodePort'
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: vector-{{ .Values.gitSha }}