---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgstac
  labels:
    app: pgstac
spec:
  selector:
    matchLabels:
      app: pgstac
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pgstac
    spec:
      restartPolicy: Always
      containers:
        - name: pgstac
          image: ghcr.io/stac-utils/pgstac:v0.7.1
          args:
            - "postgres"
            - "-N"
            - "500"
          envFrom:
            # NOTE: there's no reason we need to use a `ConfigMap` or `Secret` here to get os env vars into the pod.
            # we could just template them out here immediately with `value: $_` but this allows us
            # to store them in k8s intermediately and change them and then bounce deploys if needed
          - secretRef:
              name: pgstac-secrets
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgstac-claim
      volumes:
        - name: pgstac-claim
          persistentVolumeClaim:
            claimName: pgstac-claim