---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgstac-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.settings.resources.requests.storage }}